name: norbert_cholody_cv
description: CV in web flutter application showing skills of Norbert Chołody.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.1
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  retrofit: ^4.0.3
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.4
  build_runner: ^2.4.6




flutter:

 
  uses-material-design: true

 
  assets:
    - images/
